### PR TITLE
Make LocalBox Send if T: Send and Sync if T: Sync

### LINKED ISSUE #5: Add CopySid wrapper that copies to a non-local "Box" instead of a LocalBox
LocalBox have a fairly large downside: They cannot be safely sent across threads. It'd be nice to have a `CopySid` variant that would store the Sid in a kind of Box that can be shared across threads. Using `std::alloc::Box<Sid>` wouldn't work though, as `Sid` is an opaque type, it doesn't have a proper layout. A separate Box type would be necessary.

EDIT: On further consideration, I don't see why LocalBox is !Send !Sync. I can't find anything in windows indicating that LocalAlloc/LocalFree have threading invariants. It feels like they could be Send if T is Send, and Sync if T is Sync.

### PR DESCRIPTION
**Pull request by roblabla**
I'm *pretty sure* this is sound.

Fixes #5

### CODE REVIEW

**Comment by danieldulaney** [comment]
In case you were curious, I left it !Send and !Sync for the same reason -- I just couldn't find a good reference.

After doing some more research, LocalAlloc/LocalFree are documented [here](https://docs.microsoft.com/en-us/windows/win32/memory/global-and-local-functions) as "wrapper functions that call the corresponding heap functions using a handle to the process's default heap". In the [HeapAlloc](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) docs, the `HEAP_NO_SERIALIZE` flag "should not be specified when accessing the process's default heap." I think we can infer that this means that LocalAlloc is a wrapper for HeapAlloc that does not pass HEAP_NO_SERIALIZE, so Send and Safe are OK.

Would you be able to include a `// Safety: ` comment with a brief summary and a link back to this PR? Then it should be good to merge.

**Comment by roblabla** [comment]
How does this look?

**Comment by danieldulaney** [comment]
LGTM

**Comment by danieldulaney** [comment]
FYI changes from here and #6 were published as v0.2.2 on crates.io.

**Pull request merged**
